import { StyleSheet } from 'react-native';
import { Colors } from "./theme";

export const styles = StyleSheet.create({
    contentContainer: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 30,
        paddingTop: 45,
        paddingBottom: 20,
        backgroundColor: Colors.light.background,
    },
    btnBack: {
        width: 48,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: Colors.light.text,
        flex: 1,
        textAlign: 'center',
        marginRight: 48,
    },
    placeholder: {
        width: 48,
    },
    container: {
        paddingBottom: 120,
    },
    bannerContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    imgBanner: {
        width: '100%',
        height: 320,
        backgroundColor: Colors.light.backgroundSecondary,
        borderRadius: 12,
    },
    content: {
        paddingHorizontal: 24,
        paddingTop: 32,
        paddingBottom: 16,
    },
    titlePrin: {
        fontSize: 32,
        fontWeight: '800',
        color: Colors.light.text,
        textAlign: 'center',
        lineHeight: 38,
        marginBottom: 16,
        letterSpacing: -0.5,
    },
    descriptionPrin: {
        fontSize: 16,
        color: Colors.light.textSecondary,
        textAlign: 'center',
        lineHeight: 24,
        marginBottom: 32,
    },
    statsContainer: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 40,
    },
    statCard: {
        flex: 1,
        minWidth: 140,
        backgroundColor: 'rgba(238, 108, 43, 0.1)',
        borderRadius: 12,
        padding: 20,
        borderWidth: 1,
        borderColor: 'rgba(238, 108, 43, 0.2)',
    },
    statTitle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    statLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: Colors.light.colorPrimary,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    statValue: {
        fontSize: 24,
        fontWeight: '700',
        color: Colors.light.text,
    },
    featuresContainer: {
        gap: 16,
        marginBottom: 32,
    },
    featureItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 16,
    },
    featureIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(238, 108, 43, 0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    txtFeature: {
        flex: 1,
    },
    featureTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: Colors.light.text,
        marginBottom: 4,
    },
    featureDescription: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        lineHeight: 20,
    },
  btnContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: Colors.light.background,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 50,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.05)',
    alignItems: 'center',
},
   btnStart: {
    backgroundColor: Colors.light.colorPrimary,
    borderRadius: 12,
    paddingVertical: 18,
    paddingHorizontal: 28,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
    maxWidth: 320,
},
    btnTxt: {
        color: Colors.light.background,
        fontSize: 16,
        fontWeight: '700',
    },
    progressContainer: {
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    txtProgress: {
        color: Colors.light.textSecondary,
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
        marginBottom: 12,
    },
    barProgress: {
        height: 8,
        backgroundColor: 'rgba(238, 108, 43, 0.2)',
        borderRadius: 4,
        overflow: 'hidden',
    },
    fillProgress: {
        height: '100%',
        backgroundColor: Colors.light.colorPrimary,
        borderRadius: 4,
    },
    questionContainer: {
        paddingHorizontal: 16,
        paddingTop: 32,
        paddingBottom: 24,
    },
    txtQuestion: {
        fontSize: 24,
        fontWeight: '700',
        color: Colors.light.text,
        lineHeight: 32,
    },
    optionsContainer: {
        paddingHorizontal: 16,
        gap: 16,
    },
    option: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        backgroundColor: Colors.light.background,
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: 'transparent',
    },
    optionSelected: {
        borderColor: Colors.light.colorPrimary,
    },
    iconBox: {
        width: 48,
        height: 48,
        borderRadius: 8,
        backgroundColor: Colors.light.background,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconBoxSelected: {
        backgroundColor: 'rgba(238, 108, 43, 0.1)',
    },
    txtOption: {
        flex: 1,
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '500',
    },
    txtOptionSelected: {
        fontWeight: '600',
    },
    radioCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: Colors.light.textSecondary,
    },
    checkCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: Colors.light.colorPrimary,
        alignItems: 'center',
        justifyContent: 'center',
    },
});

export default styles;