import { StyleSheet } from 'react-native';
import { Colors } from '../constants/theme';

const stylesWL = StyleSheet.create({
    contentContainer: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 30,
        paddingTop: 45,
        paddingBottom: 20,
        backgroundColor: Colors.light.background,
    },
    btnBack: {
        width: 48,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: Colors.light.text,
        flex: 1,
        textAlign: 'center',
        marginRight: 48,
    },
    cardContainer: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 32,
    },
    backCard: {
        position: 'absolute',
        left: 32,
        right: 32,
        bottom: 0,
        height: '100%',
        borderRadius: 24,
        backgroundColor: '#e2e8f0',
        transform: [{ translateY: 16 }, { scale: 0.92 }],
        opacity: 0.5,
    },
    middleCard: {
        position: 'absolute',
        left: 28,
        right: 28,
        bottom: 0,
        height: '100%',
        borderRadius: 24,
        backgroundColor: '#cbd5e1',
        transform: [{ translateY: 8 }, { scale: 0.96 }],
        opacity: 0.8,
    },
    cardContent: {
        flex: 1,
        backgroundColor: Colors.light.background,
        borderRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
    },
    imgContainer: {
        height: 416,
        width: '100%',
        position: 'relative',
        aspectRatio: 0.75,
    },
    imgBook: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    tagGenre: {
        position: 'absolute',
        top: 16,
        left: 16,
        backgroundColor: Colors.light.colorPrimary,
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 16,
    },
    txtGenre: {
        color: Colors.light.background,
        fontSize: 12,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    detailsContainer: {
        flex: 1,
        padding: 24,
        justifyContent: 'space-between',
    },
    bookTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: Colors.light.text,
        lineHeight: 28,
        marginBottom: 4,
    },
    authorName: {
        fontSize: 14,
        fontWeight: '500',
        color: Colors.light.textSecondary,
        marginBottom: 12,
    },
    description: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        lineHeight: 20,
    },
    statsContainer: {
        flexDirection: 'row',
        gap: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: Colors.light.borderColor,
    },
    stat: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    txtStat: {
        fontSize: 12,
        fontWeight: '600',
        color: Colors.light.text,
    },
    btnAction: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 24,
        paddingHorizontal: 40,
        paddingBottom: 40,
    },
    btnDiscard: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: Colors.light.background,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
    },
    btnSave: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: Colors.light.colorPrimary,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: Colors.light.colorPrimary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
});

export default stylesWL;