import { StyleSheet } from 'react-native';
import { Colors } from './theme';

const styles = StyleSheet.create({
    contentContainer: {
        flex: 1,
        backgroundColor: Colors.light.background,
    },
    container: {
        paddingBottom: 40,
    },
    content: {
        flex: 1,
        paddingTop: 24,
        paddingHorizontal: 24,
    },
    searchSection: {
        marginBottom: 40,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        borderRadius: 16,
        paddingHorizontal: 16,
        height: 64,
    },
    searchInput: {
        flex: 1,
        marginLeft: 12,
        fontSize: 16,
        color: Colors.light.text,
        fontWeight: '500',
    },
    searchIcon: {
        marginRight: 12,
    },
    listHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 24,
    },
    listTitle: {
        fontSize: 28,
        fontWeight: '900',
        color: Colors.light.text,
        letterSpacing: -1,
    },
    listTitleHighlight: {
        color: Colors.light.colorPrimary,
    },
    listSubtitle: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        marginTop: 4,
        fontWeight: '500',
    },
    actionsContainer: {
        flexDirection: 'row',
        gap: 8,
    },
    btnAction: {
        padding: 8,
        backgroundColor: Colors.light.backgroundBadge,
        borderRadius: 8,
    },
    listContainer: {
        gap: 16,
    },
    rowCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'white',
        padding: 16,
        marginBottom: 8,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#ee6c2b1a',
    },
    rowMainSection: {
        flex: 2,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    avatar: {
        width: 56,
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
        backgroundColor: Colors.light.background,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
    },
    txtAvatar: {
        fontSize: 18,
        fontWeight: '800',
        color: Colors.light.icon,
    },
    itemInfo: {
        flex: 1,
        gap: 4,
    },
    rowTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#0f172a',
        lineHeight: 20,
    },
    rowSubtitle: {
        fontSize: 12,
        color: '#94a3b8',
        fontWeight: '500',
    },
    rowActions: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 8,
    },
    badge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    roleBadge: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        backgroundColor: '#ee6c2b1a',
    },
    badgePrimary: {
        backgroundColor: '#ee6c2b1a',
    },
    badgeSecondary: {
        backgroundColor: '#f1f5f9',
    },
    roleBadgeSecondary: {
        backgroundColor: '#f1f5f9',
    },
    txtRole: {
        fontSize: 10,
        fontWeight: '800',
        letterSpacing: 0.5,
        color: Colors.light.colorPrimary,
        textTransform: 'uppercase',
    },
    roleTxtSecondary: {
        color: '#64748b',
    },
    btnDelete: {
        padding: 8,
        backgroundColor: '#fef2f2',
        borderRadius: 8,
    },
    fabContainer: {
        position: 'absolute',
        bottom: 30,
        right: 24,
    },
    fab: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.light.colorPrimary,
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderRadius: 16,
        gap: 12,
    },
    txtFab: {
        color: 'white',
        fontWeight: '800',
        fontSize: 12,
        letterSpacing: 1.5,
    },
    titleContainer: { 
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
        gap: 16,
    },
    titleSection: {
        flex: 1,
    },
    card: {
        backgroundColor: 'white',
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
    },
    form: {
        gap: 24,
        flexDirection: 'column',
    },
    inputGroup: {
        flex: 1,
        gap: 8,
    },
    label: {
        fontSize: 11,
        fontWeight: '700',
        color: Colors.light.colorPrimary,
        letterSpacing: 1.5,
        textTransform: 'uppercase',
        marginLeft: 4,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.light.backgroundBadge,
        borderRadius: 12,
        height: 56,
        paddingHorizontal: 12,
    },
    iconLeft: {
        marginRight: 12,
    },
    iconRight: {
        marginLeft: 8,
    },
    input: {
        flex: 1,
        fontSize: 15,
        fontWeight: '500',
        color: Colors.light.text,
        height: '100%',
    },
    infoBox: {
        flexDirection: 'row',
        backgroundColor: 'rgba(238, 108, 43, 0.08)',
        padding: 16,
        borderRadius: 16,
        gap: 12,
        borderWidth: 1,
        borderColor: 'rgba(238, 108, 43, 0.1)',
    },
    infoContent: {
        flex: 1,
    },
    infoTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: Colors.light.colorPrimary,
        letterSpacing: 1,
        textTransform: 'uppercase',
    },
    txtInfo: {
        fontSize: 13,
        color: Colors.light.textSecondary,
        lineHeight: 20,
        marginTop: 4,
    },
    btnRow: {
        flexDirection: 'column',
        gap: 12,
        marginTop: 8,
    },
    btnPrimary: {
        flexDirection: 'row',
        height: 56,
        backgroundColor: Colors.light.colorPrimary,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
    },
    btnTxtPrimary: {
        color: 'white',
        fontSize: 15,
        fontWeight: '700',
    },
    btnSecondary: {
        height: 56,
        backgroundColor: 'gray',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    btnTxtSecondary: {
        color: 'white',
        fontSize: 15,
        fontWeight: '700',
    },
    infoCardsContainer: {
        flexDirection: 'row',
        gap: 16,
        marginTop: 32,
    },
    infoCard: {
        flex: 1,
        backgroundColor: 'white',
        padding: 20,
        alignItems: 'center',
        borderRadius: 20,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
    },
    infoCardIcon: {
        width: 48,
        height: 48,
        backgroundColor: Colors.light.backgroundBadge,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    infoCardTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: Colors.light.text,
        letterSpacing: 1,
        textTransform: 'uppercase',
        marginBottom: 8,
    },
    txtInfoCard: {
        fontSize: 12,
        color: Colors.light.textSecondary,
        textAlign: 'center',
        lineHeight: 18,
    },
    dropdown: {
        backgroundColor: Colors.light.backgroundBadge,
        borderRadius: 12,
        marginTop: 8,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    dropdownItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.borderColor,
    },
    dropdownItemActive: {
        backgroundColor: 'rgba(238, 108, 43, 0.1)',
    },
    dropdownTxt: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        fontWeight: '500',
    },
    dropdownTxtActive: {
        color: Colors.light.colorPrimary,
        fontWeight: '700',
    },
    btnDisabled: {
        opacity: 0.6,
    },

    //Books
    tableHeader: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: Colors.light.backgroundSecondary,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light.borderColor,
        marginBottom: 8,
    },
    headerCell: {
        flex: 1,
        fontSize: 10,
        fontWeight: '800',
        color: 'gray',
        textTransform: 'uppercase',
        letterSpacing: 1,
    },
    coverContainer: {
        width: 48,
        height: 72,
        borderRadius: 8,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cover: {
        width: '100%',
        height: '100%',
    },
    txtAuthor: {
        flex: 1,
        fontSize: 13,
        color: '#475569',
        fontWeight: '600',
    },
    ratingContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    txtRating: {
        fontSize: 14,
        fontWeight: '700',
        color: Colors.light.colorPrimary,
    },
    statusBadge: {
        flex: 1,
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 12,
        alignItems: 'center',
    },
    listContent: {
        paddingBottom: 100,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
        gap: 12,
    },
    txtEmpty: {
        fontSize: 14,
        color: Colors.light.textSecondary,
        fontWeight: '500',
    },
    tagsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 12,
    },
    tag: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ee6c2b1a',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        gap: 6,
        borderWidth: 1,
        borderColor: '#ee6c2b33',
    },
    txtTag: {
        fontSize: 12,
        fontWeight: '600',
        color: Colors.light.colorPrimary,
    },
    iconContainer: {
        width: 64,
        height: 64,
        backgroundColor: '#F3703215',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
        position: 'relative',
    },
    uploadTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: Colors.light.text,
        letterSpacing: 0.5,
        marginBottom: 8,
    },
    uploadSubtitle: {
        fontSize: 13,
        color: 'gray',
        textAlign: 'center',
        marginBottom: 12,
        lineHeight: 18,
    },
    uploadContainer: {
        height: 180,
        justifyContent: 'center',
        alignItems: 'center',
        borderStyle: 'dashed',
        flexDirection: 'column',
    },
    placeholderContent: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    imagePreviewContainer: {
        width: '100%',
        height: 300,
        backgroundColor: 'white',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: Colors.light.borderColor,
        overflow: 'hidden',
        position: 'relative',
        marginTop: 8,
    },
    imagePreview: {
        width: '100%',
        height: '100%',
    },
    btnRemove: {
        position: 'absolute',
        top: 12,
        right: 12,
        backgroundColor: 'rgba(0,0,0,0.6)',
        padding: 8,
        borderRadius: 20,
        zIndex: 10,
    }
});

export default styles;